CREATE TABLE kanjidict (
    kanji             text primary key not null, 
    radical           text not null, 
    radvar            text, 
    phonetic          text, 
    idc               text not null, 
    type              text, 
    reg_on            text, 
    reg_kun           text, 
    onyomi            text, 
    kunyomi           text, 
    nanori            text, 
    strokes           integer not null, 
    grade             text not null, 
    jlpt              text, 
    kanken            text, 
    frequency         integer, 
    meaning           text not null, 
    compact_meaning   text, 
    rtk1_3_old        integer, 
    rtk1_3_new        integer, 
    ko2001            integer, 
    ko2301            integer, 
    wrp_jkf           integer, 
    wanikani          integer)
